yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name = 'index'),
    # Страницы сообществ 
    path('group/<slug:slug>/', views.group_posts, name = 'group_list'),
] 

yatube/yatube/urls.py
from django.contrib import admin
# Функция include позволит использовать path() из других файлов.
# Импортируем!
from django.urls import include, path 


urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace = 'posts')),
    # Если в приложении posts не найдётся совпадений -
    # Django продолжит искать совпадения здесь, в головном файле urls.py.
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
# Из модуля auth импортируем функцию get_user_model 
from django.contrib.auth import get_user_model

User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add = True)
    author = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="posts"
    )

yatube/posts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Post, Group
from django.shortcuts import render, get_object_or_404

# Create your views here.
def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context) 
    

yatube/templates/base.html
<!DOCTYPE html>
{% load static %} 
<html lang="ru">          
  <head> 
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}EBLO?{% endblock %}</title>   
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Eblo?
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<div class="footer-copyright text-center py-3">© 2020 Copyright 
    <p><span style="color:red">Ya</span>tube</p> 
</div> 

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
        <span style="color:red">Ya</span>tube
      </a>
    </div>
  </nav>

yatube/templates/posts/group_list.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %} 
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    {% include 'includes/base.html' %}
    <title>{% block title %}{{ title }}{% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/base.html' %}
    </header>
    <main>
      {% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>{{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
        <article>
          {% for post in posts %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>    
          {% if post.group %}
            <p>
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </p>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        </article>
        <!-- под последним постом нет линии -->
      </div>
      {% endblock %}  
    </main>
    <footer class="page-footer font-small blue border-top">
      {% include 'includes/base.html' %}   
    </footer>
  </body>
</html>

yatube/templates/posts/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %} 
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    {% include 'includes/base.html' %}
    <title>{% block title %}{{ title }}{% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/base.html' %}
    </header>
    <main> 
      {% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        {% for post in posts %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>    
          {% if post.group %}
            <p><a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a></p>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
      </div>  
      {% endblock %}
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      {% include 'includes/base.html' %}    
    </footer>
  </body>
</html>